spring:
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ranking?charSet=UTF8}
    driver-class-name: org.postgresql.Driver


#spring.jpa.database-platform=org.hibernate.dialect.Postgre9SQLDialect
#spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto=create